Development
oneleif/UnityDebugConsole pull request #7
Opened 2020-04-10 15:48 UTC by FuhrmannMaciej

Set UI for debug console, refactored code and is now able to add and use commands.

2020-04-10 20:34 UTC, 0xLeif commented on Runtime/Scripts/DeveloperConsole.cs
> +                    if (inputText.text != "")
Could you just have one if statement? 

`if (consoleCanvas.gameObject.activeInHierarchy && Input.GetKeyDown(KeyCode.Return) && inputText.text != "") { ... }`

2020-04-10 20:41 UTC, 0xLeif commented on Runtime/Scripts/DeveloperConsole.cs
> +                Commands[input[0]].RunCommand();
Why only use the first input?

2020-04-10 20:45 UTC, 0xLeif commented on Runtime/Scripts/DeveloperConsole.cs
> +            DeveloperConsole.AddCommandsToConsole(Command, this);
🤔 Weird that a ConsoleCommand knows about a Singleton...

2020-04-10 20:46 UTC, 0xLeif commented on Runtime/Scripts/DeveloperConsole.cs
> +    public abstract class ConsoleCommand
This could be an Interface

2020-04-10 20:48 UTC, 0xLeif commented on Runtime/Scripts/Commands/CommandQuit.cs
> +            return new CommandQuit();
🤔 This seems a bit unnecessary ...

2020-04-10 20:50 UTC, 0xLeif commented on Runtime/Scripts/DeveloperConsole.cs
> +            AddMessageToConsole(message);
```
string color = type.Equals(LogType.Warning) ? "yellow" : "white";
AddMessageToConsole("<color=" + color + ">[" + type.ToString() + "]" + logMessage + "</color> ");
```

2020-04-11 18:10 UTC, 0xLeif approved these changes

2020-04-11 19:34 UTC, ambid17 requested changes
this code does not need to be merged to master

2020-04-11 20:29 UTC, FuhrmannMaciej commented
closing PR for now

2020-04-11 20:29 UTC, closed without merging